version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "monthly"
    default_labels:
      - "frontend"
      - "dependencies"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    default_labels:
      - "ci"
      - "dependencies"
  - package_manager: "python"
    directory: "/"
    update_schedule: "monthly"
    default_labels:
      - "backend"
      - "dependencies"
  - package_manager: "docker"
    directory: "/backend/ecs_tasks/delete_files"
    update_schedule: "monthly"
    default_labels:
      - "backend"
      - "dependencies"
