AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon S3 Find and Forget DDB Tables

Resources:

  DeletionQueueTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: MatchId
          AttributeType: S
        -
          AttributeName: CreatedAt
          AttributeType: N
      KeySchema: 
        - 
          AttributeName: MatchId
          KeyType: HASH
        -
          AttributeName: CreatedAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  DataMapperTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: DataMapperId
          AttributeType: S
      KeySchema:
        -
          AttributeName: DataMapperId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  JobTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TimeToLiveSpecification:
        AttributeName: Expires
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      AttributeDefinitions:
        -
          AttributeName: Id
          AttributeType: S
        -
          AttributeName: Sk
          AttributeType: S
        -
          AttributeName: GSIBucket
          AttributeType: S
        -
          AttributeName: CreatedAt
          AttributeType: N
      KeySchema:
        -
          AttributeName: Id
          KeyType: HASH
        -
          AttributeName: Sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        -
          IndexName: Date-GSI
          KeySchema:
            -
              AttributeName: GSIBucket
              KeyType: HASH
            -
              AttributeName: CreatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  DeletionQueueTable:
    Value: !Ref DeletionQueueTable
  DataMapperTable:
    Value: !Ref DataMapperTable
  JobTable:
    Value: !Ref JobTable
  JobTableDateGSI:
    Value: Date-GSI
  JobTableStreamArn:
    Value: !GetAtt JobTable.StreamArn
