AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Amazon S3 Find and Forget Layers

Resources:
  AWSSDKLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWSSDK
      Description: Latest confirmed compatible AWS SDK
      ContentUri: ../backend/lambda_layers/aws_sdk/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete
  BotoUtils:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: BotoUtils
      Description: Helpful boto3 utils
      ContentUri: ../backend/lambda_layers/boto_utils/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete
  CustomResourceHelper:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CustomResourceHelper
      Description: Helper for CloudFormation Custom Resources
      ContentUri: ../backend/lambda_layers/cr_helper/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete
  Decorators:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Decorators
      Description: Helpful function decorators
      ContentUri: ../backend/lambda_layers/decorators/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete

Outputs:
  AWSSDKLayer:
    Description: AWS SDK Layer
    Value: !Ref AWSSDKLayer
  BotoUtils:
    Description: Boto Utils Layer
    Value: !Ref BotoUtils
  CustomResourceHelper:
    Description: Custom Resource Helper Layer
    Value: !Ref CustomResourceHelper
  Decorators:
    Description: Decorators Layer
    Value: !Ref Decorators
