AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Amazon S3 Find and Forget (uksb-1q2j8beb0)

Parameters:
  AccessControlAllowOriginOverride:
    Description: Overrides the default Allow-Control-Allow-Origin setting for the API and Reports Bucket. When "false" the only origin allowed is the Web UI url. This must be set to "*" if no restriction is required.
    Type: String
    Default: "false"
  AdminEmail:
    Description: Creates a username to be used for authentication. It needs to be an e-mail address.
    Type: String
    AllowedPattern: ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$
  AthenaConcurrencyLimit:
    Description: How many Athena queries should be scheduled concurrently
    Type: Number
    Default: 20 
  AthenaWorkGroup:
    Description: WorkGroup to use for Athena queries
    Type: String
    Default: primary
  CreateCloudFrontDistribution:
    Description: Creates a CloudFront distribution for accessing the web interface of the solution. This must be enabled if S3 Block Public Access is enabled at an account level.
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  DeletionTaskCPU:
    Description: The CPU to be allocated to the Deletion Fargate Task
    Type: String
    Default: '4096'
  DeletionTasksMaxNumber:
    Description: The maximum number of tasks to allocate for the Deletion Fargate job
    Type: Number
    Default: 3
    MinValue: 1
  DeletionTaskMemory:
    Description: The memory to be allocated to the Deletion Fargate Task
    Type: String
    Default: '30720'
  EnableContainerInsights:
    Description: Enable ECS Container Insights
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
  PreBuiltArtefactsBucketOverride:
    Description: Overrides the default Bucket containing Front-end and Back-end pre-built artefacts. When false, the default is used for the given region (for example solution-builders-us-west-1)
    Type: String
    Default: "false"
  ResourcePrefix:
    Description: The prefix used for uniquely named resources, such as State Machines, etc.
    Type: String
    Default: S3F2
    AllowedPattern: ^[a-zA-Z0-9]*$
  SafeMode:
    Description: Whether to enable safe mode. When enabled, the solution will not overwrite the original object when forgetting but instead save a copy
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  VpcSecurityGroups:
    Description: List of security groups to apply to Fargate tasks
    Type: CommaDelimitedList
  VpcSubnets:
    Description: List of subnets to deploy Fargate tasks in
    Type: CommaDelimitedList
  WaitDurationQueryExecution:
    Description: Wait interval for checking if a query has completed
    Type: Number
    Default: 3
  WaitDurationQueryQueue:
    Description: Wait interval for checking Find progress
    Type: Number
    Default: 3
  WaitDurationForgetQueue:
    Description: Wait interval for checking Forget progress
    Type: Number
    Default: 30

Conditions:
  DefaultPreBuiltArtefactsBucket: !Equals [!Ref PreBuiltArtefactsBucketOverride, "false"]

Mappings:
  Solution:
    Constants:
      Version: '0.1'

Resources:
  TempBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: ExpireContents
            Status: Enabled
            ExpirationInDays: 1
            NoncurrentVersionExpirationInDays: 1

  ConfigParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /s3f2/${ResourcePrefix}-Configuration
      Type: String
      Value: !Sub |
        {
          "AthenaConcurrencyLimit": ${AthenaConcurrencyLimit},
          "DeletionTasksMaxNumber": ${DeletionTasksMaxNumber},
          "SafeMode": ${SafeMode},
          "WaitDurationQueryExecution": ${WaitDurationQueryExecution},
          "WaitDurationQueryQueue": ${WaitDurationQueryQueue},
          "WaitDurationForgetQueue": ${WaitDurationForgetQueue}
        }
      Description: SSM Parameter for S3F2 configuration.

  APIStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./api.yaml
      Parameters:
        AccessControlAllowOriginOverride: !Ref AccessControlAllowOriginOverride
        ConfigParameter: !Ref ConfigParameter
        CognitoUserPoolArn: !GetAtt AuthStack.Outputs.CognitoUserPoolArn
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        DataMapperTableName: !GetAtt DDBStack.Outputs.DataMapperTable
        JobTableDateGSI: !GetAtt DDBStack.Outputs.JobTableDateGSI
        JobTableName: !GetAtt DDBStack.Outputs.JobTable
        JobTableStreamArn: !GetAtt DDBStack.Outputs.JobTableStreamArn
        StateMachineArn: !GetAtt StateMachineStack.Outputs.StateMachineArn
        WebUIOrigin: !GetAtt WebUIStack.Outputs.Origin
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./auth.yaml
      Parameters:
        AdminEmail: !Ref AdminEmail
        ResourcePrefix: !Ref ResourcePrefix
  DDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ddb.yaml
  DelStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./deletion_flow.yaml
      Parameters:
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.CustomResourceHelper
            - !GetAtt LayersStack.Outputs.Decorators
        DeletionTaskCPU: !Ref DeletionTaskCPU
        DeletionTaskMemory: !Ref DeletionTaskMemory
        EnableContainerInsights: !Ref EnableContainerInsights
        JobTableName: !GetAtt DDBStack.Outputs.JobTable
        ResourcePrefix: !Ref ResourcePrefix
        SafeModeBucket: !Ref TempBucket
        VpcSecurityGroups: !Join [",", !Ref VpcSecurityGroups]
        VpcSubnets: !Join [",", !Ref VpcSubnets]
  DeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./deployment_helper.yaml
      Parameters:
        ApiUrl: !GetAtt APIStack.Outputs.ApiUrl
        AthenaExecutionRole: !GetAtt StateMachineStack.Outputs.AthenaExecutionRole
        CodeBuildArtefactBucket: !Ref TempBucket
        CognitoIdentityPoolId: !GetAtt AuthStack.Outputs.CognitoIdentityPoolId
        CognitoUserPoolId: !GetAtt AuthStack.Outputs.CognitoUserPoolId
        CognitoUserPoolClientId: !GetAtt AuthStack.Outputs.CognitoUserPoolClientId
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.BotoUtils
            - !GetAtt LayersStack.Outputs.CustomResourceHelper
            - !GetAtt LayersStack.Outputs.Decorators
        CreateCloudFrontDistribution: !Ref CreateCloudFrontDistribution
        DeleteTaskRole: !GetAtt DelStack.Outputs.DeleteTaskRole
        ECRRepository: !GetAtt DelStack.Outputs.ECRRepository
        PreBuiltArtefactsBucket: !If [DefaultPreBuiltArtefactsBucket, !Sub "solution-builders-${AWS::Region}", !Ref PreBuiltArtefactsBucketOverride]
        ResourcePrefix: !Ref ResourcePrefix
        Version: !FindInMap [Solution, Constants, Version]
        WebUIBucket: !GetAtt WebUIStack.Outputs.WebUIBucket
  LayersStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./layers.yaml
  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./state_machine.yaml
      Parameters:
        AthenaWorkGroup: !Ref AthenaWorkGroup
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
        DataMapperTableName: !GetAtt DDBStack.Outputs.DataMapperTable
        DeleteServiceName: !GetAtt DelStack.Outputs.DeleteServiceName
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        DeleteQueueUrl: !GetAtt DelStack.Outputs.DeleteObjectsQueueUrl
        ECSCluster: !GetAtt DelStack.Outputs.ECSCluster
        JobTableName: !GetAtt DDBStack.Outputs.JobTable
        ResultBucket: !Ref TempBucket
        StateMachinePrefix: !Ref ResourcePrefix
        WebUIOrigin: !GetAtt WebUIStack.Outputs.Origin
  WebUIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./web_ui.yaml
      Parameters:
        CreateCloudFrontDistribution: !Ref CreateCloudFrontDistribution
        ResourcePrefix: !Ref ResourcePrefix

Outputs:
  APIAccessControlAllowOriginHeader:
    Value: !GetAtt APIStack.Outputs.AccessControlAllowOriginHeader
  APIStack:
    Value: !Ref APIStack
  ApiUrl:
    Value: !GetAtt APIStack.Outputs.ApiUrl
  AthenaStateMachineArn:
    Value: !GetAtt StateMachineStack.Outputs.AthenaStateMachineArn
  AthenaExecutionRoleArn:
    Value: !GetAtt StateMachineStack.Outputs.AthenaExecutionRoleArn
  ConfigParameter:
    Value: !Ref ConfigParameter
  CognitoUserPoolClientId:
    Value: !GetAtt AuthStack.Outputs.CognitoUserPoolClientId
  CognitoUserPoolId:
    Value: !GetAtt AuthStack.Outputs.CognitoUserPoolId
  DataMapperTable:
    Value: !GetAtt DDBStack.Outputs.DataMapperTable
  DDBStack:
    Value: !Ref DDBStack
  DeleteTaskRoleArn:
    Value: !GetAtt DelStack.Outputs.DeleteTaskRoleArn
  DeletionQueueTable:
    Value: !GetAtt DDBStack.Outputs.DeletionQueueTable
  DeletionQueueUrl:
    Value: !GetAtt DelStack.Outputs.DeleteObjectsQueueUrl
  DLQUrl:
    Value: !GetAtt DelStack.Outputs.DLQUrl
  ECRRepository:
    Value: !GetAtt DelStack.Outputs.ECRRepository
  JobTable:
    Value: !GetAtt DDBStack.Outputs.JobTable
  QueryQueueUrl:
     Value: !GetAtt StateMachineStack.Outputs.QueryQueueUrl
  StateMachineArn:
    Value: !GetAtt StateMachineStack.Outputs.StateMachineArn
  StateMachineRoleArn:
    Value: !GetAtt StateMachineStack.Outputs.StateMachineRoleArn
  TempBucket:
    Value: !Ref TempBucket
  WebUIBucket:
    Value: !GetAtt WebUIStack.Outputs.WebUIBucket
  WebUIUrl:
    Value: !GetAtt WebUIStack.Outputs.Url

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Required"
        Parameters:
          - AdminEmail
          - SafeMode
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcSecurityGroups
          - VpcSubnets
          - CreateCloudFrontDistribution
          - AccessControlAllowOriginOverride
      - Label:
          default: "Performance Configuration"
        Parameters:
          - AthenaConcurrencyLimit
          - DeletionTasksMaxNumber
          - DeletionTaskCPU
          - DeletionTaskMemory
      - Label:
          default: "Waiter Configuration"
        Parameters:
          - WaitDurationQueryExecution
          - WaitDurationQueryQueue
          - WaitDurationForgetQueue
      - Label:
          default: "Advanced Configuration"
        Parameters:
          - AthenaWorkGroup
          - EnableContainerInsights
          - PreBuiltArtefactsBucketOverride
          - ResourcePrefix
