AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon S3 Find and Forget Web UI

Parameters:
  AccessLogsBucket:
    Type: String
    Default: ""
  CreateCloudFrontDistribution:
    Type: String
  DeployWebUI:
    Type: String
  ResourcePrefix:
    Type: String

Conditions:
  WithAccessLogs: !Not [!Equals [!Ref AccessLogsBucket, ""]]
  ShouldDeployWebUI: !Equals [!Ref DeployWebUI, "true"]
  WithCloudFront: !And
    - !Equals [!Ref CreateCloudFrontDistribution, "true"]
    - !Condition ShouldDeployWebUI

Resources:

  WebUIBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: !If
          - WithCloudFront
          - True
          - False
        RestrictPublicBuckets: !If
          - WithCloudFront
          - True
          - False
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET]
            AllowedOrigins: ["*"]
            Id: !Sub ${ResourcePrefix}CorsRule
            MaxAge: 3600
      LoggingConfiguration: !If
        - WithAccessLogs
        - DestinationBucketName: !Ref AccessLogsBucket
          LogFilePrefix: !Sub ${ResourcePrefix}/
        - !Ref AWS::NoValue

  WebUIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ShouldDeployWebUI
    Properties:
      Bucket: !Ref WebUIBucket
      PolicyDocument:
        Statement:
          - Sid: HttpsOnly
            Action: '*'
            Effect: Deny
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${WebUIBucket}
              - !Sub arn:${AWS::Partition}:s3:::${WebUIBucket}/*
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - !If
            - WithCloudFront
            - Sid: CloudFrontOriginOnly
              Action: s3:GetObject
              Effect: Allow
              Resource: !Sub arn:${AWS::Partition}:s3:::${WebUIBucket}/*
              Principal:
                Service: cloudfront.amazonaws.com
              Condition:
                StringEquals:
                  "AWS:SourceArn": !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution.Id}"
            - Sid: AllowDirectAccess
              Action: s3:GetObject
              Effect: Allow
              Resource: !Sub arn:${AWS::Partition}:s3:::${WebUIBucket}/*
              Principal: "*"

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Condition: WithCloudFront
    Properties:
      OriginAccessControlConfig:
        Description: S3F2 Web UI
        Name: !Sub "${ResourcePrefix}-WebUI-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: WithCloudFront
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebUIBucket.RegionalDomainName
            Id: !Sub ${ResourcePrefix}-myS3Origin
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig: {}
        Enabled: true
        HttpVersion: http2
        Comment: The Distribution for Amazon S3 Find and Forget
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          TargetOriginId: !Sub ${ResourcePrefix}-myS3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Logging: !If
          - WithAccessLogs
          - Bucket: !Sub ${AccessLogsBucket}.s3.${AWS::URLSuffix}
            IncludeCookies: false
            Prefix: !Sub ${ResourcePrefix}/
          - !Ref AWS::NoValue

Outputs:
  CloudFrontDistribution:
    Value: !If
      - WithCloudFront
      - !Ref CloudFrontDistribution
      - "none"
  Origin:
    Value: !If
      - WithCloudFront
      - !Sub "https://${CloudFrontDistribution.DomainName}"
      - !Sub "https://${WebUIBucket.RegionalDomainName}"
    Description: Web UI Origin
  Url:
    Value: !If
      - WithCloudFront
      - !Sub "https://${CloudFrontDistribution.DomainName}"
      - !Sub "https://${WebUIBucket.RegionalDomainName}/index.html"
    Description: Web UI Url
  WebUIBucket:
    Value: !Ref WebUIBucket
    Description: Web UI S3 Bucket
